### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by japgolly** [liancheng/scalafix-organize-imports#64]
Hey. I just tried 0.3.1-RC2 and am seeing a new error:

```
[error] java.lang.StackOverflowError
[error] 	at scala.meta.internal.semanticdb.Scala$ScalaSymbolOps.isNone(Scala.scala:38)
[error] 	at scalafix.v1.Symbol.isNone(Symbol.scala:13)
[error] 	at scalafix.internal.v1.InternalSemanticDoc.info(InternalSemanticDoc.scala:65)
[error] 	at scalafix.v1.SemanticDocument.info(SemanticDocument.scala:38)
[error] 	at scalafix.v1.Symbol.info(Symbol.scala:21)
[error] 	at fix.OrganizeImports$SymbolSafeInfo.$anonfun$safeInfo$1(OrganizeImports.scala:631)
[error] 	at scala.util.Try$.apply(Try.scala:213)
[error] 	at fix.OrganizeImports$SymbolSafeInfo.safeInfo(OrganizeImports.scala:631)
[error] 	at fix.OrganizeImports.toRef$1(OrganizeImports.scala:223)
[error] 	at fix.OrganizeImports.toRef$1(OrganizeImports.scala:225)
[error] 	at fix.OrganizeImports.toRef$1(OrganizeImports.scala:225)
[error] 	at fix.OrganizeImports.toRef$1(OrganizeImports.scala:225)
[error] 	at fix.OrganizeImports.toRef$1(OrganizeImports.scala:225)
[error] 	at fix.OrganizeImports.toRef$1(OrganizeImports.scala:225)
[error] 	at fix.OrganizeImports.toRef$1(OrganizeImports.scala:225)
[error] 	at fix.OrganizeImports.toRef$1(OrganizeImports.scala:225)
[error] 	at fix.OrganizeImports.toRef$1(OrganizeImports.scala:225)
[error] 	at fix.OrganizeImports.toRef$1(OrganizeImports.scala:225)
[error] 	at fix.OrganizeImports.toRef$1(OrganizeImports.scala:225)
[error] 	at fix.OrganizeImports.toRef$1(OrganizeImports.scala:225)
[error] 	at fix.OrganizeImports.toRef$1(OrganizeImports.scala:225)
[error] 	at fix.OrganizeImports.toRef$1(OrganizeImports.scala:225)
[error] 	at fix.OrganizeImports.toRef$1(OrganizeImports.scala:225)
```

**Comment by japgolly** [comment]
Unfortunately I can't work out exactly which set of imports causes this.

**Comment by liancheng** [comment]
@japgolly, thanks for reporting! Any chance that you are using imports beginning with `_root_.`?

**Comment by japgolly** [comment]
No, not directly *but* there's a very good chance that some macros I'm using generate code that includes imports from `_root_`.

**Comment by liancheng** [comment]
I've been quite busy recently and didn't get a chance to look into this issue.

My hunch is that for some `Symbol`s, their `owner` method return `Symbols.None`, whose `owner` is also a `Symbols.None`. In this case, we may fall into an infinite loop. But I failed to construct a case where this can happen.

@japgolly, is your project publicly available on GitHub? In that case, I can run `OrganizeImports` against your repo and debug with extra logging to locate the root cause.

**Comment by japgolly** [comment]
Unfortunately I can't share the code but I printed some debugging info out when these cases occur:


```
=====================================================================================================
importer = scalaz.{Equal, Order}
importer.ref = scalaz

symbol = <no symbol>
symbol.displayName = 
symbol.isNone = true
symbol.isEmptyPackage = false

owner = <no symbol>

symbol.infoNoThrow exists (_.isPackageObject) = false

SemanticDocument(/home/golly/BeardedLogic/projects/shipreq/Code/webapp-macro/shared/src/main/scala/shipreq/webapp/base/util/GenericData.scala)
=====================================================================================================
[info] Running scalafix on 5 Scala sources
[info] Running scalafix on 4 Scala sources
[info] Running scalafix on 23 Scala sources
[info] Running scalafix on 4 Scala sources
=====================================================================================================
importer = shipreq.base.util.ErrorMsg
importer.ref = shipreq.base.util

symbol = <no symbol>
symbol.displayName = 
symbol.isNone = true
symbol.isEmptyPackage = false

owner = <no symbol>

symbol.infoNoThrow exists (_.isPackageObject) = false

SemanticDocument(/home/golly/BeardedLogic/projects/shipreq/Code/webapp-base-test/js/src/main/scala/shipreq/webapp/base/protocol/websocket/WebSocketServerHelper.scala)
=====================================================================================================
=====================================================================================================
importer = shipreq.base.util.IndexLabel._
importer.ref = shipreq.base.util.IndexLabel

symbol = <no symbol>
symbol.displayName = 
symbol.isNone = true
symbol.isEmptyPackage = false

owner = <no symbol>

symbol.infoNoThrow exists (_.isPackageObject) = false

SemanticDocument(/home/golly/BeardedLogic/projects/shipreq/Code/base-test/shared/src/main/scala/shipreq/base/test/UseCaseStepUtils.scala)
=====================================================================================================
[info] Running scalafix on 4 Scala sources
[info] Running scalafix on 29 Scala sources
[info] Running scalafix on 43 Scala sources
[info] Running scalafix on 9 Scala sources
=====================================================================================================
importer = shipreq.webapp.base.util.ReqCodeTreeItem
importer.ref = shipreq.webapp.base.util

symbol = <no symbol>
symbol.displayName = 
symbol.isNone = true
symbol.isEmptyPackage = false

owner = <no symbol>

symbol.infoNoThrow exists (_.isPackageObject) = false

SemanticDocument(/home/golly/BeardedLogic/projects/shipreq/Code/webapp-base-member/shared/src/main/scala/shipreq/webapp/base/text/PlainText.scala)
=====================================================================================================
=====================================================================================================
importer = shipreq.webapp.base.protocol.websocket.ProjectSpaProtocols.WsReqRes.{ProjectNameSet => _, _}
importer.ref = shipreq.webapp.base.protocol.websocket.ProjectSpaProtocols.WsReqRes

symbol = <no symbol>
symbol.displayName = 
symbol.isNone = true
symbol.isEmptyPackage = false

owner = <no symbol>

symbol.infoNoThrow exists (_.isPackageObject) = false

SemanticDocument(/home/golly/BeardedLogic/projects/shipreq/Code/webapp-server-logic/shared/src/main/scala/shipreq/webapp/server/logic/MakeEvent.scala)
=====================================================================================================
=====================================================================================================
importer = shipreq.webapp.base.util.CharSubset.EscapeChars
importer.ref = shipreq.webapp.base.util.CharSubset

symbol = <no symbol>
symbol.displayName = 
symbol.isNone = true
symbol.isEmptyPackage = false

owner = <no symbol>

symbol.infoNoThrow exists (_.isPackageObject) = false

SemanticDocument(/home/golly/BeardedLogic/projects/shipreq/Code/webapp-base/shared/src/main/scala/shipreq/webapp/base/util/CharSubset.scala)
=====================================================================================================
```

What's interesting about this is that I tried taking these files and turning them into tests but they don't throw in isolation. Even outside of tests, if I run `scalafix` on just a single module (instead of from the root module where it does everything) the error doesn't occur.

**Comment by liancheng** [comment]
@japgolly, which version were you using when adding the debugging logs? Those `scalaz` imports are already fully-qualified. Not sure about the `shipreq` ones. The current master should only pass relative imports into the `expandRelative` method. Were you still using 3.1.0-RC2?

**Comment by liancheng** [comment]
@japgolly, did you shade `scalaz` into another package?

**Comment by japgolly** [comment]
Hi @liancheng . I was using the `master` branch of this project at that time, and no, scalaz wasn't shaded; just a normal import from `_root_`

**Comment by liancheng** [comment]
@japgolly, the reason why a fully-qualified importer was still passed into `expandRelative` is that the `isFullyQualifed` function didn't take care of `Symbols.None`, and therefore treated those imports as relative ones. Made a minor adjustment in https://github.com/liancheng/scalafix-organize-imports/commit/d4ac2f673d13ac59525898fbdf8506b9dfcfd75a to make it clearer.

That being said, it's still not clear to me why sometimes the symbol information is not available and whether it's safe to always assume that the importer is fully-qualified. But since all the cases you hit are fully-qualified imports, we can tentatively assume that is true.

**Comment by liancheng** [comment]
> What's interesting about this is that I tried taking these files and turning them into tests but they don't throw in isolation. Even outside of tests, if I run `scalafix` on just a single module (instead of from the root module where it does everything) the error doesn't occur.

@japgolly, after re-reading this paragraph, I was thinking, is it possible that it's because the corresponding `.semanticsdb` file(s) couldn't be properly located when Scalafix was executed from the root module? This explains why some symbols are missing only when you run from the root module but not in isolated tests or other modules.

**Comment by bjaglin** [comment]
> @japgolly, after re-reading this paragraph, I was thinking, is it possible that it's because the corresponding `.semanticsdb` file(s) couldn't be properly located when Scalafix was executed from the root module?

That could be it indeed. https://github.com/scalacenter/scalafix/issues/1245 looks like the same problem, although I can't figure out what's going on.
